### ISSUE TITLE
Add own-instance properties: `aref` and `vref`

### ISSUE THREAD

**Issue by rwaldron** [julianduque/beaglebone-io#21]
See: https://github.com/rwaldron/johnny-five/issues/892

For BeagleBone: 
- `ahref = 1.8`
- `vref = 3.3`

This can be read-only accessors, or just plain properties, which ever you prefer.

**Comment by rwaldron** [comment]
cc @gnarf

**Comment by gnarf** [comment]
wait -- `ahref` or `vref`??  I thought you said `aref` - do i need to update Temp?

**Comment by rwaldron** [comment]
> wait -- ahref or vref??

Both—these can be different values.

> do i need to update Temp?

No, Temp will only need `aref`.

**Comment by fivdi** [comment]
I'm sorry for taking so long to respond to this issue which is addressed by PR #32.

**Comment by julianduque** [comment]
v2.0.0 has been published, thanks to great work by @fivdi
