### ISSUE TITLE
Unable to use USR0, 1 and 2 pins

### ISSUE THREAD

**Issue by championswimmer** [julianduque/beaglebone-io#23]
I see from the code that they are not yet supported yet. Any special reasons why ?

**Comment by julianduque** [comment]
Currently we are using an Arduino compatible pin mapping, we have an open issue to support BBB pinout schema #1, will see if we can have this implemented asap

**Comment by fivdi** [comment]
I'm sorry that it took so long to respond to this issue. PR #32 addresses this issue and if merged will enable access to USR0, 1 and 2.

**Comment by julianduque** [comment]
v2.0.0 has been published, thanks to great work by @fivdi
