### ISSUE TITLE
Drop support for Node.js v0.10, v0.12, v5 and v7

### ISSUE THREAD

**Issue by fivdi** [julianduque/beaglebone-io#61]
[beagleboard.org](https://beagleboard.org/latest-images) provide Debian Jessie images with Node.js v4 and the Debian Stretch images with Node.js v6. Supporting Node.js v0.10 and v0.12 is therefore no longer necessary.

**Comment by julianduque** [comment]
@fivdi yesm I agree, we can publish another major. 4.0.0
